### ISSUE TITLE
Jupyter Server Roadmap

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#2]
In today's call, we put together a technical roadmap for the Jupyter Server. Here's a place to discuss the plan.

---

- [x] Release [nbclassic](https://github.com/zsailer/nbclassic)
    - [x] a notebook `ExtensionApp` (from jupyter_server).
    - [x] pulls Notebook JS and templates from `notebook`.
    - [x] execute from command line with `jupyter nbclassic`
    - [x] migrates configuration to `jupyter_server_config`.
- [x] Setup Jupyter Server's Testing Framework
    - [x] Port old tests to pytest.
    - [x] Move to Github actions (?) 
- [ ] Merge Kernel Providers
    - [ ] Move jupyter_kernel_mgmt, jupyter_protocol to Jupyter's Github org.
    - [ ] Documentation for Kernel Providers, jupyter_kernel_mgmt and jupyter_protocol.
    - [ ] Merge Kernel Providers into jupyter_server: jupyter/jupyter_server#112.
    - [ ] Help voila adjust to kernel_mgmt
        - @kevin-bates mentioned that he spoke with @SylvainCorlay about KP.
    - [ ] Release jupyter_server with Kernel Providers
    - [ ] Help`nb_conda_kernels` switch to Kernel Providers.
        - They currently have an old version of Kernel Provider.
        - nb_conda_kernels tries to import Kernel Providers. If found, uses the new kernel management framework. Otherwise, falls back to old way.
- [ ] Update Jupyter Server JEP to reflect new nbclassic.
- [ ] Transition other frontends:
    - JupyterLab to Jupyter Server, dropping notebook as a dependency.
    - nteract_on_jupyter to Jupyter Server
    - any other frontends?
    - Uses nbclassic to run multiple frontends side-by-side.
- [ ] Notebook 7.x: transition jupyter/notebook to Jupyter Server
    - [ ] drop the old notebook server
    - [ ] NotebookApp becomes
    - [ ] shim the notebook server API to jupyter_server
    - [ ] raise DeprecationWarnings in shimmed APIs.
    - [ ] release notebook 7.x
- [ ] Notebook 8.x: drop shims.

**Comment by Zsailer** [comment]
Closing this issue, as this roadmap is very out-of-date. We'll work on developing a new roadmap in the new year, once a Jupyter Server Team is established.

**Comment by saiwing-yeung** [comment]
Where will the new roadmap be communicated?
